import fs from "node:fs";
import path from "node:path";

import type { ProjectTracking, TrackingMode } from "../types.js";

import { atomicWriteFile } from "./atomic.js";
import {
  DEFAULT_RUNTIME_RELATIVE_PATH,
  DEFAULT_STATE_RELATIVE_PATH,
  DEFAULT_STATE_TRACKING,
} from "./constants.js";
import { stateError } from "./errors.js";
import type { StatePaths, StateRecordKind, TrackingLayout } from "./types.js";
import { STATE_RECORD_KINDS } from "./types.js";

const TRACKING_MODES = new Set<TrackingMode>(["git", "local", "ephemeral"]);

function isTrackingMode(value: unknown): value is TrackingMode {
  return typeof value === "string" && TRACKING_MODES.has(value as TrackingMode);
}

export function normalizeTracking(tracking: ProjectTracking | undefined): ProjectTracking {
  const merged: ProjectTracking = {
    ...DEFAULT_STATE_TRACKING,
    ...tracking,
  };
  for (const [key, mode] of Object.entries(merged)) {
    if (!isTrackingMode(mode)) {
      stateError(
        "configuration_invalid",
        "state_tracking_invalid",
        `Invalid tracking mode "${String(mode)}" for ${key}`,
        { key, mode },
      );
    }
  }
  return merged;
}

export function classifyTracking(tracking: ProjectTracking): TrackingLayout {
  const ignored: StateRecordKind[] = [];
  const git: StateRecordKind[] = [];
  const ephemeral: StateRecordKind[] = [];
  for (const kind of STATE_RECORD_KINDS) {
    const mode = tracking[kind];
    if (mode === "local") {
      ignored.push(kind);
    } else if (mode === "git") {
      git.push(kind);
    } else {
      ephemeral.push(kind);
    }
  }
  return {
    tracking,
    ignoredKinds: ignored,
    gitKinds: git,
    ephemeralKinds: ephemeral,
  };
}

export function resolveStatePaths(options: {
  projectRoot: string;
  statePath?: string;
  runtimePath?: string;
  tracking: ProjectTracking;
}): StatePaths {
  const stateRelative = options.statePath ?? DEFAULT_STATE_RELATIVE_PATH;
  const runtimeRelative = options.runtimePath ?? DEFAULT_RUNTIME_RELATIVE_PATH;
  if (path.isAbsolute(stateRelative) || path.isAbsolute(runtimeRelative)) {
    stateError(
      "invalid_input",
      "state_path_absolute",
      "State and runtime paths must be project-relative",
      { statePath: stateRelative, runtimePath: runtimeRelative },
    );
  }
  const state = path.join(options.projectRoot, stateRelative);
  const runtime = path.join(options.projectRoot, runtimeRelative);
  const kindPath = (kind: StateRecordKind): string => {
    if (options.tracking[kind] === "ephemeral") {
      return path.join(runtime, "state", kind);
    }
    return path.join(state, kind);
  };
  return {
    root: options.projectRoot,
    state,
    runtime,
    tasks: kindPath("tasks"),
    results: kindPath("results"),
    decisions: kindPath("decisions"),
    approvals: kindPath("approvals"),
    verifications: kindPath("verifications"),
    events: kindPath("events"),
    claims: path.join(runtime, "claims"),
    locks: path.join(runtime, "locks"),
  };
}

export function applyTrackingLayout(paths: StatePaths, layout: TrackingLayout): void {
  fs.mkdirSync(paths.state, { recursive: true });
  fs.mkdirSync(paths.runtime, { recursive: true });
  for (const directory of [
    paths.tasks,
    paths.results,
    paths.decisions,
    paths.approvals,
    paths.verifications,
    paths.events,
    paths.claims,
    paths.locks,
  ]) {
    fs.mkdirSync(directory, { recursive: true });
  }

  const lines = [
    "# Generated by state:repository (spec §8.3).",
    "# local kinds are ignored; git kinds are committed; ephemeral kinds live under runtime/.",
  ];
  for (const kind of STATE_RECORD_KINDS) {
    if (layout.tracking[kind] === "local") {
      lines.push(`/${kind}/`);
    }
  }
  lines.push("");
  atomicWriteFile(path.join(paths.state, ".gitignore"), `${lines.join("\n")}`);

  // Runtime is always ephemeral and must never be committed.
  atomicWriteFile(path.join(paths.runtime, ".gitignore"), "*\n");
}

export function directoryForKind(paths: StatePaths, kind: StateRecordKind): string {
  switch (kind) {
    case "tasks":
      return paths.tasks;
    case "results":
      return paths.results;
    case "decisions":
      return paths.decisions;
    case "approvals":
      return paths.approvals;
    case "verifications":
      return paths.verifications;
    case "events":
      return paths.events;
    default: {
      const exhaustive: never = kind;
      return exhaustive;
    }
  }
}
