export function dashboardHtml(token: string): string {
  const safeToken = JSON.stringify(token).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VibeKit Project Dashboard</title>
<style>
:root{color-scheme:dark;--paper:#11120f;--panel:#191b17;--line:#34372f;--ink:#f3f0e7;--muted:#aaa99f;--signal:#d9ff57;--warn:#ff9e52;--bad:#ff6d62;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink)}button,input{font:inherit}button{border:1px solid var(--line);background:#24271f;color:var(--ink);padding:.6rem .8rem;cursor:pointer}button:hover{border-color:var(--signal)}button:focus-visible,input:focus-visible{outline:3px solid var(--signal);outline-offset:2px}button.danger{color:var(--bad)}button:disabled{opacity:.45;cursor:wait}
header{border-bottom:1px solid var(--line);padding:2rem clamp(1rem,4vw,4rem);display:flex;align-items:end;justify-content:space-between;gap:2rem}.eyebrow{color:var(--signal);letter-spacing:.12em;text-transform:uppercase;font-size:.75rem}h1{font-family:Georgia,serif;font-size:clamp(2.2rem,6vw,5rem);font-weight:400;line-height:.9;margin:.3rem 0 0}.gateway{color:var(--muted);text-align:right}.gateway strong{display:block;color:var(--ink);font-size:1.2rem}
main{padding:1.5rem clamp(1rem,4vw,4rem) 4rem}.toolbar,.counts{display:flex;gap:.7rem;align-items:center;flex-wrap:wrap}.toolbar{justify-content:space-between;margin-bottom:1.5rem}.counts span{border-left:2px solid var(--line);padding-left:.6rem;color:var(--muted)}.counts b{color:var(--ink)}
.dashboard{border-top:1px solid var(--line)}article{display:grid;grid-template-columns:minmax(14rem,1.3fr) minmax(11rem,.8fr) minmax(14rem,1fr) auto;gap:1rem;padding:1.25rem 0;border-bottom:1px solid var(--line);align-items:start}h2{font-family:Georgia,serif;font-weight:400;margin:0 0 .35rem;font-size:1.5rem}.id,.path,.meta{color:var(--muted);font-size:.78rem;overflow-wrap:anywhere}.path{margin-top:.45rem}.state{display:inline-flex;align-items:center;gap:.45rem;text-transform:uppercase;font-size:.72rem;letter-spacing:.08em}.state:before{content:"";width:.6rem;height:.6rem;border-radius:50%;background:var(--muted)}.state.running:before{background:var(--signal)}.state.starting:before{background:var(--warn)}.state.unhealthy:before,.state.invalid:before{background:var(--bad)}.state.missing:before{background:transparent;border:1px solid var(--bad)}.facts{display:grid;grid-template-columns:auto 1fr;gap:.3rem .7rem;font-size:.8rem}.facts dt{color:var(--muted)}.facts dd{margin:0}.actions{display:flex;justify-content:flex-end;gap:.4rem;flex-wrap:wrap;max-width:20rem}.empty{padding:5rem 0;color:var(--muted)}
dialog{width:min(50rem,calc(100% - 2rem));border:1px solid var(--line);background:var(--panel);color:var(--ink);padding:0}dialog::backdrop{background:#000b}.dialog-head{display:flex;justify-content:space-between;align-items:center;padding:1rem;border-bottom:1px solid var(--line)}.dialog-body{padding:1rem}label{display:block;color:var(--muted);font-size:.8rem;margin-bottom:.5rem}input{width:100%;border:1px solid var(--line);background:var(--paper);color:var(--ink);padding:.8rem}.dialog-actions{display:flex;justify-content:flex-end;gap:.5rem;margin-top:1rem}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:60vh;overflow:auto;font-size:.75rem;color:#d7d5cd}.error{color:var(--bad);min-height:1.2em}
@media(max-width:900px){article{grid-template-columns:1fr 1fr}.actions{justify-content:flex-start;max-width:none}}@media(max-width:580px){header{align-items:start;flex-direction:column}.gateway{text-align:left}article{grid-template-columns:1fr}.toolbar{align-items:stretch}.toolbar>div:last-child{display:grid;grid-template-columns:1fr 1fr}.actions{display:grid;grid-template-columns:1fr 1fr}.actions button{width:100%}}
</style>
</head>
<body>
<header><div><div class="eyebrow">Local operations / isolated hosts</div><h1>Project Dashboard</h1></div><div class="gateway"><span id="gateway-state">Gateway online</span><strong id="clock">—</strong><span>127.0.0.1</span></div></header>
<main>
<div class="toolbar"><div class="counts" id="counts" aria-live="polite"></div><div><button id="add">Add existing</button> <button id="start-all">Start all</button> <button class="danger" id="stop-all">Stop all</button></div></div>
<section class="dashboard" id="dashboard" aria-label="Registered Projects"></section><p class="error" id="error" role="alert"></p>
</main>
<dialog id="prompt"><form method="dialog"><div class="dialog-head"><strong id="prompt-title">Project path</strong><button value="cancel" aria-label="Close">×</button></div><div class="dialog-body"><label for="project-path">Absolute path to an existing VibeKit Project</label><input id="project-path" autocomplete="off" required><p class="error" id="prompt-error"></p><div class="dialog-actions"><button value="cancel">Cancel</button><button id="prompt-submit" value="default">Continue</button></div></div></form></dialog>
<dialog id="logs"><div class="dialog-head"><strong id="logs-title">Host log</strong><button id="logs-close" aria-label="Close">×</button></div><div class="dialog-body"><pre id="log-text"></pre></div></dialog>
<dialog id="config"><div class="dialog-head"><strong id="config-title">Effective configuration</strong><button id="config-close" aria-label="Close">×</button></div><div class="dialog-body"><pre id="config-text"></pre></div></dialog>
<script>
const TOKEN=${safeToken};const headers={"content-type":"application/json","x-vibekit-token":TOKEN};const dashboard=document.querySelector("#dashboard"),error=document.querySelector("#error"),prompt=document.querySelector("#prompt"),pathInput=document.querySelector("#project-path");let projects=[],projectMarkup="";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...headers,...options.headers}});const body=await response.json().catch(()=>({error:response.statusText}));if(!response.ok)throw new Error(body.error||response.statusText);return body}
function controls(p){if(p.state==="missing")return '<button data-action="locate">Locate</button>';if(p.state==="invalid")return '<button data-action="locate">Locate</button><button class="danger" data-action="remove">Remove</button>';const running=p.state==="running"||p.state==="unhealthy";return '<button data-action="'+(running?'stop':'start')+'">'+(running?'Stop':'Start')+'</button><button data-action="restart">Restart</button><button data-action="config">Config</button><button data-action="open">Open folder</button><button data-action="logs">View logs</button><button class="danger" data-action="remove">Remove</button>'}
function pairingMarkup(p){const pairings=p.pairings||{owner:null,paired:[],pending:[]};const owner=pairings.owner?'<dt>Owner</dt><dd>'+esc(pairings.owner.displayName||pairings.owner.userId)+'</dd>':'';const pending=pairings.pending||[];const rows=pending.map(item=>'<div class="pairing"><span>'+esc(item.displayName||item.userId)+' · code '+esc(item.code)+'</span><button data-action="approve-pairing" data-code="'+esc(item.code)+'">Approve</button></div>').join('');return (owner||rows)?'<div class="pairings"><strong>Telegram pairing</strong><dl class="facts">'+owner+'</dl>'+rows+'</div>':''}
function render(data){projects=data.projects;const c=data.counts;document.querySelector("#counts").innerHTML='<span><b>'+projects.length+'</b> projects</span><span><b>'+c.running+'</b> running</span><span><b>'+(c.unhealthy+c.invalid+c.missing)+'</b> attention</span>';document.querySelector("#clock").textContent=new Date(data.generatedAt).toLocaleTimeString();const markup=projects.length?projects.map(p=>'<article data-id="'+esc(p.projectId)+'"><div><h2>'+esc(p.name||p.projectId)+'</h2><div class="id">'+esc(p.projectId)+'</div><div class="path">'+esc(p.path)+'</div></div><div><span class="state '+p.state+'">'+esc(p.state)+'</span><div class="meta">'+(p.pid?'PID '+p.pid:'No process')+(p.startedAt?' · '+esc(new Date(p.startedAt).toLocaleString()):'')+'</div></div><dl class="facts"><dt>Agent</dt><dd>'+esc(p.defaultAgent||'—')+'</dd><dt>Bindings</dt><dd>'+esc(p.agentBindings.join(', ')||'—')+'</dd><dt>Model</dt><dd>'+esc(p.provider&&p.model?p.provider+' / '+p.model:'—')+'</dd><dt>Interfaces</dt><dd>'+esc(Object.entries(p.interfaces).map(([n,h])=>n+' '+(h.connected?'connected':h.detail||'offline')).join(', ')||'—')+'</dd><dt>Work</dt><dd>'+p.activeConversations+' active · '+p.queuedTurns+' queued</dd>'+(p.lastFatalError?'<dt>Error</dt><dd>'+esc(p.lastFatalError)+'</dd>':'')+'</dl><div class="actions">'+controls(p)+'</div>'+pairingMarkup(p)+'</article>').join(''):'<div class="empty">No Projects registered. Add an existing Project to begin.</div>';if(markup!==projectMarkup){dashboard.innerHTML=markup;projectMarkup=markup}}
async function refresh(){try{render(await api('/api/projects'));error.textContent='';document.querySelector('#gateway-state').textContent='Gateway online'}catch(e){error.textContent=e.message;document.querySelector('#gateway-state').textContent='Gateway unavailable'}}
async function mutate(url,options={}){error.textContent='';try{await api(url,{method:'POST',...options});await refresh()}catch(e){error.textContent=e.message}}
dashboard.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;const row=button.closest('article'),id=row.dataset.id,action=button.dataset.action,encoded=encodeURIComponent(id);button.disabled=true;if(action==='start'||action==='restart'){const badge=row.querySelector('.state');badge.className='state starting';badge.textContent='starting'}try{if(action==='approve-pairing'){await api('/api/projects/'+encoded+'/pairings/'+encodeURIComponent(button.dataset.code)+'/approve',{method:'POST'})}else if(action==='logs'){const data=await api('/api/projects/'+encoded+'/logs');document.querySelector('#logs-title').textContent=id+' / host.log';document.querySelector('#log-text').textContent=data.logs||'No log output.';document.querySelector('#logs').showModal()}else if(action==='config'){const data=await api('/api/projects/'+encoded+'/config');document.querySelector('#config-title').textContent=id+' / effective config';document.querySelector('#config-text').textContent=JSON.stringify(data.project,null,2);document.querySelector('#config').showModal()}else if(action==='remove'){if(confirm('Unregister '+id+'? Project files and State will remain.'))await api('/api/projects/'+encoded,{method:'DELETE'})}else if(action==='locate'){openPrompt('Locate '+id,async path=>api('/api/projects/'+encoded+'/locate',{method:'POST',body:JSON.stringify({path})}))}else await mutate('/api/projects/'+encoded+'/'+action)}catch(e){error.textContent=e.message}finally{button.disabled=false;await refresh()}});
function openPrompt(title,submit){document.querySelector('#prompt-title').textContent=title;document.querySelector('#prompt-error').textContent='';pathInput.value='';prompt.showModal();prompt.onsubmit=async e=>{e.preventDefault();try{await submit(pathInput.value);prompt.close();await refresh()}catch(err){document.querySelector('#prompt-error').textContent=err.message}}}
document.querySelector('#add').onclick=()=>openPrompt('Add existing Project',path=>api('/api/projects',{method:'POST',body:JSON.stringify({path})}));document.querySelector('#start-all').onclick=()=>mutate('/api/projects/start-all');document.querySelector('#stop-all').onclick=()=>{if(confirm('Stop every running Project Host?'))mutate('/api/projects/stop-all',{body:JSON.stringify({confirm:true})})};document.querySelector('#logs-close').onclick=()=>document.querySelector('#logs').close();document.querySelector('#config-close').onclick=()=>document.querySelector('#config').close();refresh();setInterval(refresh,2000);
</script>
</body></html>`;
}
